project:
  type: website
  output-dir: docs

website:
  title: "Bethany Gardner"
  navbar:
    left:
      - href: index.qmd
        text: About

format:
  html:
    theme: pulse
    toc: false
    embed-resources: true
