project:
  type: website
  output-dir: docs

website:
  title: "Bethany Gardner"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: pubs.qmd
        text: Papers & Presentations
      - href: freelance.qmd
        text: Freelance
      - text: Portfolio Projects
        menu:
          - href: https://bethanyhgardner.github.io/dissertation/
            text: Dissertation published as Quarto book
          - href: https://bethanyhgardner.github.io/lingthusiasm-vowel-plots/
            text: Vowel plots tutorial
          - href: https://github.com/bethanyhgardner/llm-size-plot/
            text: LLM size data & plot
      - text: CV/Resume
        menu:
          - href: https://github.com/bethanyhgardner/bethanyhgardner.github.io/blob/main/industry_resume.pdf
            text: Industry
          - href: https://github.com/bethanyhgardner/bethanyhgardner.github.io/blob/main/academic_CV.pdf
            text: Academic
  page-footer:
    center: Made using Quarto v1.5

format:
  html:
    page-layout: full
    theme: pulse
    toc: false
    embed-resources: true
