project:
  type: website

website:
  title: "Bethany Gardner"
  navbar:
    left:
      - href: index.qmd
        text: About

format:
  html:
    theme: pulse
    toc: false
    embed-resources: true
